export default [
  { link: '/', title: 'Home' },
  { link: '/login', title: 'Login' },
  { link: '/comments', title: 'Comments' },
  { link: '/community', title: 'Community Messages' },
  { link: '/like', title: 'Like' },
  { link: '/share', title: 'Share' },
  { link: '/group', title: 'Community' },
  { link: '/playlist', title: 'Playlist' },
  { link: '/contact', title: 'Contact Us' },
  { link: '/subscribe', title: 'Subscribe to Author' },
  { link: '/recommend', title: 'Recommendations' },
  { link: '/poll', title: 'Poll' },
  { link: '/post', title: 'Post' },
  { link: '/app', title: 'Application' },
  { link: '/article', title: 'Article' },
  { link: '/allow-messages-from-community', title: 'AllowMessagesFromCommunity' },
];
